### ISSUE TITLE
Only allow eclipse-tractusx helm charts

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#110]
**Reason**
Add k8s policy to only allow eclipse-tractusx helm charts on deployment.
This policy might need to be implemented in either ArgoCD OR/And kyverno

**AC**

- Env: starting with stable; Make it easy to configure/add to all other environments

**Additional information / links**

**Comment by carslen** [comment]
With ETX release 3.2/23.09 the stable environment is limited to allow only Eclipse-Tractusx helm charts. This has been implemented using Argo Project definition:

```yaml
[...]
sourceRepos:
    - https://eclipse-tractusx.github.io/charts/dev
[...]
```

With the project setting `sourceRepos` you can limit which sources can be used in ArgoCD Apps. The default setup for every env, except of STABLE is `*` which allows any resource.

Investigating alternative configuration using Kyverno instead of ArgoCD project setup.

**Comment by carslen** [comment]
A Kyverno policy to limit the usage of Eclipse-Tractusx Helm repository could look like this:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-etx-helm-repository-usage
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: helm-repository
      match:
        any:
          - resources:
              kinds:
                - Application
      validate:
        message: >-
          Using sources other than Eclipse-Tractusx Helm Repository is not allowed.
        anyPattern:
          spec:
            source:
              repoURL: https://eclipse-tractusx.github.io/charts/dev

```

https://github.com/catenax-ng/product-onboarding/blob/chore/kyverno-policy-helm-repo/kyverno/policies-enforce/require-etx-helm-repo.yaml
